version: '3'
services:
  database:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/aplication
    volumes:
      - ../../../data:/var/lib/postgresql/data/aplication
  pgadmin:
    image: dpage/pgadmin4:4
    ports:
      - "8000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=training@test.pl
      - PGADMIN_DEFAULT_PASSWORD=admin
